export * from './header/Header';
export * from './header/Title';
export * from './carrousel/Carrousel';
export * from './category-card/CategoryCard';
export * from './modern-card/ModernCard';
export * from './simple-card/SimpleCard';
export * from './big-card/BigCard';
export * from './footer/Footer';
export * from './pagination/Pagination';